/** Declaration file generated by dts-gen */

export interface A {
	XXX: number;
}
export interface ServerObject {
	front: boolean,
	name: string,
	detect: string,
	internal: string,
	external: string,
	network: string,
	id: string,
}

export const whoAmI: ServerObject;
export const serverMap: {[id: string]: ServerObject};

export function forEach(cb: (obj: ServerObject)=> void): void;
export function some(cb: (obj: ServerObject)=> boolean): boolean;
